import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { styled } from "@mui/material/styles";
import Button from "@mui/material/Button";
import UserUploadRegion from "../src/hooks/useUploadRegion";
import { useState, useRef } from "react";
import Stack from "@mui/material/Stack";
const Input = styled("input")({
  display: "none",
});

const UploadArea = styled("div")(({ theme }) => ({
  width: "100%",
  maxWidth: "25rem",
  backgroundColor: "#ffff",
  boxShadow: "0 10px 60px rgb(218, 229, 255)",
  border: "2px solid rgb(171, 202, 255)",
  borderRadius: "24px",
  padding: "2rem 1.875rem 5rem 1.875rem",
  margin: "0.625rem",
  textAlign: "center",
}));
const UploadTitle = styled("div")(({ theme }) => ({
  fontSize: "1.8rem",
  fontWeight: 500,
  marginBottom: "0.3125rem",
}));
const UploadSubTitle = styled("div")(({ theme }) => ({
  fontSize: "0.9375rem",
  color: "rgb(196, 195, 196)",
  marginTop: 0,
}));
const DropFileArea = styled("div")(({ theme }) => ({
  position: "relative",
  height: "11.25rem",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  flexDirection: "column",
  border: "2px dashed rgb(171, 202, 255)",
  borderRadius: "15px",
  marginTop: "2.1875rem",
  cursor: "pointer",
  transition: "border-color 300ms ease-in-out",
}));
const InputfileCustom = styled("input")(({ theme }) => ({
  position: "absolute",
  height: "100%",
  width: "100%",
  opacity: 0,
  cursor: "pointer",
}));

const Home = () => {
  const hiddenFileInput = useRef(null);
  const handleChange = async (event) => {
    if (event.target.files && event.target.files[0]) {
      const i = event.target.files[0];
      const body = new FormData();
      body.append("file", i);
      console.log(event.target.files);
      await UserUploadRegion(body);
    }
  };

  const handleClick = (event) => {
    hiddenFileInput.current.click();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <form>
          <UploadArea>
            <UploadTitle>Upload your file</UploadTitle>
            <UploadSubTitle>File should be an .kml file</UploadSubTitle>
            <DropFileArea onClick={handleClick}>
              <p>Drop your file here or Click to browse</p>
              <input
                type="file"
                ref={hiddenFileInput}
                onChange={handleChange}
                accept="image/*"
                style={{ display: "none" }}
              />
            </DropFileArea>
          </UploadArea>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
